apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-iscsi-luks
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: ""
  volumeName: media-iscsi-luks
  resources:
    requests:
      storage: 1Ti
